### PR TITLE
Add header and the footer for the page

### LINKED ISSUE #8: Site Title
## 1. site title

> assigned to Miroslav

__As a site visitor, I want to know what the web page is called__

### Repository

- [ ] developed on a branch called `site-title`

### HTML

- [ ] A `header` and `footer` element ...
- [ ] ... with the page's title : logo HFY on left side of header
- [ ] ... and class "site-title"

### CSS

- [ ] the "site-title" class

### PR DESCRIPTION
**Pull request by miroslavveljanoski**
Hi SkyBlue. I made the header and the footer for our page. Please take a look at my code.
Closes #8

### CODE REVIEW

**Review by harunaltunhr — APPROVED** [review]
It looks good, we will have some conflict whem merging. After that it will be ok

**Review by adekimpianna — APPROVED** [review]
It looks really great!! But Is there a way to make the `h1` a little to the right? 🙏

**Comment by adekimpianna** [comment]
image

How, do you agree girls? @Feruzteame @murvanessa @Boam1994

**Comment by miroslavveljanoski** [comment]
Capture

I this looks better I will push my branch again? Anyhow when we merge the first branch I think everything will be ok, but starting from the second one probably some conflicts will arise :smile:

**Comment by miroslavveljanoski** [comment]
I set the main title to the middle of the page as we agreed.

**Comment by Feruzteame** [comment]
For me it sound good !

**Comment by miroslavveljanoski** [comment]
Guys I resolve the conflicts using merging. We want to learn how to solve conflicts with rebase :smile:

**Pull request merged**
