### PR TITLE
Introduction

### PR DESCRIPTION
**Pull request by Feruzteame**

### CODE REVIEW

**Review by adekimpianna — APPROVED** [review]

**Comment by adekimpianna** [comment]
It is looking like this, horaay!  
 afbeelding

**Review by harunaltunhr — APPROVED** [review]
Well Done

**Review by miroslavveljanoski — APPROVED** [review]
It seems great to me

**Comment by miroslavveljanoski** [comment]
Because we have 3 approvals, I'm going to merge this branch to the master.

**Pull request merged**
